### ISSUE TITLE
[Feature Request]: Install via Cargo

### ISSUE THREAD

**Issue by ALameLlama** [iffse/pay-respects#4]
### What do you want us to work on?

Hey, I recently found this when looking for alternative for thefuck and it working great so far.

I was wondering if there was any plans on publishing this to crate.io so it's possible to install from any distro more easily.

e.g
cargo install tree-sitter-cli
cargo install bottom
cargo install ripgrep

**Comment by iffse** [comment]
Done, you can now install via `cargo install pay-respects` :)

Come back if there is any new issue.
