### ISSUE TITLE
[Feature Request]: built-in `command_not_found_handle` function

### ISSUE THREAD

**Issue by mokurin000** [iffse/pay-respects#9]
### What do you want us to work on?

For example, if user could see hints after a command-not-found,
they will not need to type "f" and enter to get hints

+ need to test, `shell::last_command` may work with this case

I tried:

```bash
function command_not_found_handle() {
    f; return $?
}
```

But this will not work. pay-respects finds the previous command as input, while the current latest command should be used instead.

**Comment by iffse** [comment]
Apparently, the history is added after command_not_found_handle executes

The following snippet works:
```shell
command_not_found_handler() {
	_PR_LAST_COMMAND=$1 _PR_SHELL="zsh" pay-respects
}
```

For a better user experience, a dedicated implementation in pay-respects would be required: Stricter matching conditions and suggest install if needed.

**Comment by mokurin000** [comment]
> For a better user experience, a dedicated implementation in pay-respects would be required: Stricter matching conditions and suggest install if needed.

maybe a separate issue?

**Comment by iffse** [comment]
Let's keep it here

**Comment by mokurin000** [comment]
> Apparently, the history is added after `command_not_found_handle` executes
> 
> The following snippet works:
> 
> ```shell
> command_not_found_handler() {
> 	_PR_LAST_COMMAND=$1 _PR_SHELL="zsh" pay-respects
> }
> ```
> 
> For a better user experience, a dedicated implementation in pay-respects would be required: Stricter matching conditions and suggest install if needed.

```bash
alias f="$(pay-respects.exe bash)"

command_not_found_handle() {
    _PR_LAST_COMMAND=$1 _PR_SHELL="bash" pay-respects
}
```

With such configuration in `~/.bashrc`, I got a panic message:

```text
thread 'main' panicked at src\shell.rs:59:40:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by iffse** [comment]
> in ~/.bashrc

Because bash [is the only shell that does not return the exact](https://github.com/iffse/pay-respects/blob/61947e5a1e9db994a554ddc7c64204d3197105e0/src/shell.rs#L58) and I there's some string handling inside.

This should work for bash:
```shell
command_not_found_handle() {
    _PR_LAST_COMMAND="1 $@" _PR_SHELL="bash" pay-respects
}
```

**Comment by mokurin000** [comment]
```bash
alias f="$(pay-respects.exe bash)"

command_not_found_handle() {
    if which pay-respects &> /dev/null
    then _PR_LAST_COMMAND="_ $*" _PR_SHELL="bash" pay-respects
    else return 127
    fi
}
```
